let data = [{
    "aging_process": "New & neutral French oak ",
    "bottle_id": 1,
    "cases_produced": 99,
    "clones": ["943 "],
    "clusters": "70% ",
    "pct_alcohol": "13.0% ",
    "ph": "NULL",
    "soils": ["Sedimentary "],
    "source_file": "15_origin_johan.json",
    "ta": "NULL",
    "varietals": ["NULL"],
    "wine_name": ["Pinot Noir"],
    "winery_id": "W-8",
    "winery_name": "Origin",
    "year": "2015"
}, {
    "aging_process": "Neutral French oak ",
    "bottle_id": 2,
    "cases_produced": 49,
    "clones": ["NULL"],
    "clusters": "NULL",
    "pct_alcohol": "13.2% ",
    "ph": "3.62 ",
    "soils": ["Sedimentary "],
    "source_file": "16+Chenin+Blanc+Tech.json",
    "ta": "5.7 g/L ",
    "varietals": ["NULL"],
    "wine_name": ["Chenin Blanc"],
    "winery_id": "W-8",
    "winery_name": "Origin",
    "year": "2016"
}, {
    "aging_process": "10 months neutral French oak barriques ",
    "bottle_id": 3,
    "cases_produced": 450,
    "clones": ["Oregon Heirloom "],
    "clusters": "10% ",
    "pct_alcohol": "13.9% ",
    "ph": "3.40 ",
    "soils": ["Sedimentary "],
    "source_file": "16+Gamay+Noir.json",
    "ta": "7.3 g/L ",
    "varietals": ["NULL"],
    "wine_name": ["Gamay Noir"],
    "winery_id": "W-7",
    "winery_name": "Omero",
    "year": "2016"
}, {
    "aging_process": "neutral french oak ",
    "bottle_id": 4,
    "cases_produced": 60,
    "clones": ["NULL"],
    "clusters": "75% ",
    "pct_alcohol": "12.7% ",
    "ph": "3.69 ",
    "soils": ["Sedimentary "],
    "source_file": "16+Minimus+WV+Red.json",
    "ta": "5.8g/L ",
    "varietals": ["NULL"],
    "wine_name": ["Cabernet Franc", " Gamay Noir"],
    "winery_id": "W-6",
    "winery_name": "Minimus",
    "year": "2016"
}, {
    "aging_process": "10 months in combination of 140L Chablis casks, half barrels and neutral French barrique ",
    "bottle_id": 5,
    "cases_produced": 390,
    "clones": ["Mendoza", " 108", " Musqu\u00e9", " Old Wente", " Espiquette "],
    "clusters": "NULL",
    "pct_alcohol": "13% ",
    "ph": "3.32 ",
    "soils": ["Marine-Sedimentary", " Alluvial", " Volcanic", " "],
    "source_file": "16+Omero+Chard.json",
    "ta": "5.9 g/L ",
    "varietals": ["NULL"],
    "wine_name": ["Chardonnay"],
    "winery_id": "W-7",
    "winery_name": "Omero",
    "year": "2016"
}, {
    "aging_process": "10 months neutral French oak barriques ",
    "bottle_id": 6,
    "cases_produced": 450,
    "clones": ["Oregon Heirloom "],
    "clusters": "10% ",
    "pct_alcohol": "13.9% ",
    "ph": "3.40 ",
    "soils": ["Sedimentary "],
    "source_file": "16GamayNoir.json",
    "ta": "7.3 g/L ",
    "varietals": ["NULL"],
    "wine_name": ["Gamay Noir"],
    "winery_id": "W-7",
    "winery_name": "Omero",
    "year": "2016"
}, {
    "aging_process": "neutral French oak ",
    "bottle_id": 7,
    "cases_produced": 149,
    "clones": ["Mariafeld", " 943 "],
    "clusters": "80% ",
    "pct_alcohol": "12.8% ",
    "ph": "3.62 ",
    "soils": ["NULL"],
    "source_file": "16_dict_johan_PN+.json",
    "ta": "6.0 g/L ",
    "varietals": ["NULL"],
    "wine_name": ["Pinot Noir"],
    "winery_id": "W-6",
    "winery_name": "Minimus",
    "year": "2016"
}, {
    "aging_process": "neutral French oak ",
    "bottle_id": 8,
    "cases_produced": 25,
    "clones": ["Mendoza "],
    "clusters": "NULL",
    "pct_alcohol": "13.2% ",
    "ph": "3.36 ",
    "soils": ["Sedimentary "],
    "source_file": "16_no_Mother#24.json",
    "ta": "5.4 g/L ",
    "varietals": ["NULL"],
    "wine_name": ["Chardonnay"],
    "winery_id": "W-6",
    "winery_name": "Minimus",
    "year": "2016"
}, {
    "aging_process": "neutral French oak barriques ",
    "bottle_id": 9,
    "cases_produced": 70,
    "clones": ["NULL"],
    "clusters": "40% ",
    "pct_alcohol": "13.89% ",
    "ph": "3.48 ",
    "soils": ["NULL"],
    "source_file": "16_no_Noir#23+.json",
    "ta": "6.3 g/L ",
    "varietals": ["Pinot Noir", " Gamay Noir and Trousseau Noir "],
    "wine_name": ["NULL"],
    "winery_id": "W-6",
    "winery_name": "Minimus",
    "year": "2016"
}, {
    "aging_process": "Chestnut barriques, stainless steel ",
    "bottle_id": 10,
    "cases_produced": 98,
    "clones": ["NULL"],
    "clusters": "NULL",
    "pct_alcohol": "13.9% ",
    "ph": "3.45 ",
    "soils": ["NULL"],
    "source_file": "16_no_Pinot#22+.json",
    "ta": "5.0 g/L ",
    "varietals": ["Pinot Blanc", " Pinot Gris", " Pinot Noir", " Pinot \u201cGouges", "\u201d Pinot Meunier "],
    "wine_name": ["Pinot Noir"],
    "winery_id": "W-6",
    "winery_name": "Minimus",
    "year": "2016"
}, {
    "aging_process": "neutral French oak ",
    "bottle_id": 11,
    "cases_produced": 45,
    "clones": ["NULL"],
    "clusters": "NULL",
    "pct_alcohol": "13.69% ",
    "ph": "3.69 ",
    "soils": ["Sedimentary "],
    "source_file": "16_origin_gouges.json",
    "ta": "4.6 g/L ",
    "varietals": ["NULL"],
    "wine_name": ["Pinot Noir"],
    "winery_id": "W-8",
    "winery_name": "Origin",
    "year": "2016"
}, {
    "aging_process": "Combination Amphorae & Acacia wood casks ",
    "bottle_id": 12,
    "cases_produced": 150,
    "clones": ["NULL"],
    "clusters": "NULL",
    "pct_alcohol": "14.8% ",
    "ph": "3.47 ",
    "soils": ["NULL"],
    "source_file": "17+Amphorae+SB.json",
    "ta": "NULL",
    "varietals": ["NULL"],
    "wine_name": ["Sauvignon Blanc"],
    "winery_id": "W-6",
    "winery_name": "Minimus",
    "year": "2017"
}, {
    "aging_process": "neutral oak & new chestnut barriques ",
    "bottle_id": 13,
    "cases_produced": 120,
    "clones": ["NULL"],
    "clusters": "NULL",
    "pct_alcohol": "14.9% ",
    "ph": "3.69 ",
    "soils": ["sedimentary "],
    "source_file": "17+Min+#25.json",
    "ta": "NULL",
    "varietals": ["NULL"],
    "wine_name": ["Chardonnay"],
    "winery_id": "W-6",
    "winery_name": "Minimus",
    "year": "2017"
}, {
    "aging_process": "nuetral French oak ",
    "bottle_id": 14,
    "cases_produced": 310,
    "clones": ["NULL"],
    "clusters": "20% ",
    "pct_alcohol": "13.0% ",
    "ph": "3.51 ",
    "soils": ["varied "],
    "source_file": "17+MIn+WV+Red+Wine.json",
    "ta": "NULL",
    "varietals": ["NULL"],
    "wine_name": ["Chardonnay", " Pinot Noir"],
    "winery_id": "W-6",
    "winery_name": "Minimus",
    "year": "2017"
}, {
    "aging_process": "Acacia wood & stainless steel ",
    "bottle_id": 15,
    "cases_produced": 110,
    "clones": ["NULL"],
    "clusters": "NULL",
    "pct_alcohol": "12.5% ",
    "ph": "NULL",
    "soils": ["Volcanic "],
    "source_file": "17+muller+thurgau+tech.json",
    "ta": "NULL",
    "varietals": ["NULL"],
    "wine_name": ["M\u00fcller-Thurgau", " Riesling"],
    "winery_id": "W-6",
    "winery_name": "Minimus",
    "year": "2017"
}, {
    "aging_process": "neutral French oak barriques, half barrels and 140L Chablis casks ",
    "bottle_id": 16,
    "cases_produced": 200,
    "clones": ["Old Went\u00e9", " Calera", " Musquet", " Mount Eden", " 108 "],
    "clusters": "NULL",
    "pct_alcohol": "13.4% ",
    "ph": "3.6 ",
    "soils": ["Varied "],
    "source_file": "17+Omero+Chard.json",
    "ta": "NULL",
    "varietals": ["NULL"],
    "wine_name": ["Chardonnay"],
    "winery_id": "W-7",
    "winery_name": "Omero",
    "year": "2017"
}, {
    "aging_process": "Neutral oak ",
    "bottle_id": 17,
    "cases_produced": 460,
    "clones": ["NULL"],
    "clusters": "10% ",
    "pct_alcohol": "13.5% ",
    "ph": "3.34 ",
    "soils": ["volcanic "],
    "source_file": "17+Omero+Gamay.json",
    "ta": "NULL",
    "varietals": ["NULL"],
    "wine_name": ["Gamay Noir"],
    "winery_id": "W-7",
    "winery_name": "Omero",
    "year": "2017"
}, {
    "aging_process": "neutral French oak ",
    "bottle_id": 18,
    "cases_produced": 75,
    "clones": ["NULL"],
    "clusters": "NULL",
    "pct_alcohol": "13.6% ",
    "ph": "3.43 ",
    "soils": ["basalt "],
    "source_file": "17+Origin+Cab+Franc.json",
    "ta": "NULL",
    "varietals": ["NULL"],
    "wine_name": ["Cabernet Franc"],
    "winery_id": "W-8",
    "winery_name": "Origin",
    "year": "2017"
}, {
    "aging_process": "neutral oak ",
    "bottle_id": 19,
    "cases_produced": 150,
    "clones": ["NULL"],
    "clusters": "NULL",
    "pct_alcohol": "13.3% ",
    "ph": "NULL",
    "soils": ["Sedimentary "],
    "source_file": "17+Origin+SB+Chard.json",
    "ta": "NULL",
    "varietals": ["55% Sauvignon Blanc", " 45% Chardonnay "],
    "wine_name": ["Chardonnay", " Sauvignon Blanc"],
    "winery_id": "W-8",
    "winery_name": "Origin",
    "year": "2017"
}, {
    "aging_process": "9 mnths in combination neutral oak, Acacia wood, Chestnut barriques & puncheons ",
    "bottle_id": 20,
    "cases_produced": 110,
    "clones": ["NULL"],
    "clusters": "NULL",
    "pct_alcohol": "13.7% ",
    "ph": "NULL",
    "soils": ["Varied "],
    "source_file": "17+Rockwell.json",
    "ta": "NULL",
    "varietals": ["NULL"],
    "wine_name": ["NULL"],
    "winery_id": "W-6",
    "winery_name": "Minimus",
    "year": "2017"
}, {
    "aging_process": "Concrete ",
    "bottle_id": 21,
    "cases_produced": 883,
    "clones": ["NULL"],
    "clusters": "30% ",
    "pct_alcohol": "13.1% ",
    "ph": "NULL",
    "soils": ["Varied "],
    "source_file": "17+Sans-soufre+PN.json",
    "ta": "NULL",
    "varietals": ["NULL"],
    "wine_name": ["Pinot Noir"],
    "winery_id": "W-6",
    "winery_name": "Minimus",
    "year": "2017"
}, {
    "aging_process": "Combination concrete and neutral oak/chestnut ",
    "bottle_id": 22,
    "cases_produced": 210,
    "clones": ["NULL"],
    "clusters": "NULL",
    "pct_alcohol": "13.7% ",
    "ph": "3.41 ",
    "soils": ["Volcanic "],
    "source_file": "17+Vermentino+Tech.json",
    "ta": "NULL",
    "varietals": ["NULL"],
    "wine_name": ["Vermentino"],
    "winery_id": "W-6",
    "winery_name": "Minimus",
    "year": "2017"
}, {
    "aging_process": "neutral French oak ",
    "bottle_id": 23,
    "cases_produced": 80,
    "clones": ["NULL"],
    "clusters": "NULL",
    "pct_alcohol": "14.1% ",
    "ph": "3.31 ",
    "soils": ["basalt "],
    "source_file": "17Mendoza+Chard.json",
    "ta": "NULL",
    "varietals": ["NULL"],
    "wine_name": ["Chardonnay"],
    "winery_id": "W-6",
    "winery_name": "Minimus",
    "year": "2017"
}, {
    "aging_process": "combination neutral & new French oak ",
    "bottle_id": 24,
    "cases_produced": 30,
    "clones": ["NULL"],
    "clusters": "NULL",
    "pct_alcohol": "13.6% ",
    "ph": "3.38 ",
    "soils": ["sedimentary "],
    "source_file": "17MInCaleraChard.json",
    "ta": "NULL",
    "varietals": ["NULL"],
    "wine_name": ["Chardonnay"],
    "winery_id": "W-6",
    "winery_name": "Minimus",
    "year": "2017"
}, {
    "aging_process": "10 months in neutral oak barriques & puncheons ",
    "bottle_id": 25,
    "cases_produced": 400,
    "clones": ["NULL"],
    "clusters": "15% ",
    "pct_alcohol": "13.9% ",
    "ph": "3.45 ",
    "soils": ["NULL"],
    "source_file": "18WV+Red.json",
    "ta": "NULL",
    "varietals": ["NULL"],
    "wine_name": ["Cabernet Franc", " Pinot Gris", " Pinot Noir"],
    "winery_id": "W-6",
    "winery_name": "Minimus",
    "year": "2018"
}, {
    "aging_process": "22 months in neutral French oak barriques ",
    "bottle_id": 26,
    "cases_produced": 95,
    "clones": ["NULL"],
    "clusters": "20% ",
    "pct_alcohol": "13.8% ",
    "ph": "3.42 ",
    "soils": ["NULL"],
    "source_file": "18_dict_Gre-Syrah.json",
    "ta": "NULL",
    "varietals": ["78% Grenache", " 24% Syrah "],
    "wine_name": ["Grenache", " Syrah"],
    "winery_id": "W-6",
    "winery_name": "Minimus",
    "year": "2018"
}, {
    "aging_process": "16 months in neutral French oak barriques ",
    "bottle_id": 27,
    "cases_produced": 100,
    "clones": ["NULL"],
    "clusters": "90% ",
    "pct_alcohol": "13.9% ",
    "ph": "3.65 ",
    "soils": ["Alluvial "],
    "source_file": "18_MIN_SM3.json",
    "ta": "NULL",
    "varietals": ["100% Syrah "],
    "wine_name": ["Syrah"],
    "winery_id": "W-6",
    "winery_name": "Minimus",
    "year": "2018"
}, {
    "aging_process": "neutral french oak ",
    "bottle_id": 28,
    "cases_produced": 50,
    "clones": ["unknown "],
    "clusters": "25% ",
    "pct_alcohol": "12.7% ",
    "ph": "3.64 ",
    "soils": ["Sedimentary "],
    "source_file": "1968+PN+Chehalem.json",
    "ta": "5.8g/L ",
    "varietals": ["NULL"],
    "wine_name": ["Pinot Noir"],
    "winery_id": "W-6",
    "winery_name": "Minimus",
    "year": "2016"
}, {
    "aging_process": "second-filled french oak ",
    "bottle_id": 29,
    "cases_produced": 14,
    "clones": ["108 "],
    "clusters": "NULL",
    "pct_alcohol": "12.9% ",
    "ph": "NULL",
    "soils": ["Sedimentary "],
    "source_file": "1984+Chard.json",
    "ta": "NULL",
    "varietals": ["NULL"],
    "wine_name": ["Chardonnay"],
    "winery_id": "W-6",
    "winery_name": "Minimus",
    "year": "2016"
}, {
    "aging_process": "16 months in neutral French oak ",
    "bottle_id": 30,
    "cases_produced": 70,
    "clones": ["NULL"],
    "clusters": "NULL",
    "pct_alcohol": "12.2% ",
    "ph": "3.35 ",
    "soils": ["NULL"],
    "source_file": "19_Helix_Caroline.json",
    "ta": "NULL",
    "varietals": ["69% Chardonnay", " 31% Sauvignon blanc "],
    "wine_name": ["Chardonnay", " Sauvignon Blanc"],
    "winery_id": "W-6",
    "winery_name": "Minimus",
    "year": "2019"
}, {
    "aging_process": "7 months in neutral French oak barriques ",
    "bottle_id": 31,
    "cases_produced": 140,
    "clones": ["NULL"],
    "clusters": "NULL",
    "pct_alcohol": "12.9% ",
    "ph": "3.29 ",
    "soils": ["NULL"],
    "source_file": "19_Omero_PG.json",
    "ta": "NULL",
    "varietals": ["100% Pinot Gris "],
    "wine_name": ["Pinot Gris"],
    "winery_id": "W-7",
    "winery_name": "Omero",
    "year": "2019"
}, {
    "aging_process": "NULL",
    "bottle_id": 32,
    "cases_produced": 1700,
    "clones": ["35% Pommard", " 37% - 777", " 23% - 114", " 5% - Wadenswil "],
    "clusters": "NULL",
    "pct_alcohol": " 14.3% ",
    "ph": " 3.61 ",
    "soils": ["Laurelwood Series "],
    "source_file": "AlloroEPN17 TechSheet.json",
    "ta": " 6.10 g/L ",
    "varietals": ["NULL"],
    "wine_name": ["Pinot Noir"],
    "winery_id": "W-1",
    "winery_name": "Alloro",
    "year": "2017"
}, {
    "aging_process": "NULL",
    "bottle_id": 33,
    "cases_produced": 300,
    "clones": ["100% - Dijon 777 "],
    "clusters": "NULL",
    "pct_alcohol": " 14.2% ",
    "ph": " 3.62 ",
    "soils": ["Laurelwood Series "],
    "source_file": "AlloroJusPN17 TechSheet.json",
    "ta": " 6.20 g/L ",
    "varietals": ["NULL"],
    "wine_name": ["Pinot Noir"],
    "winery_id": "W-1",
    "winery_name": "Alloro",
    "year": "2017"
}, {
    "aging_process": "NULL",
    "bottle_id": 34,
    "cases_produced": 100,
    "clones": ["NULL"],
    "clusters": "NULL",
    "pct_alcohol": " 12.0% ",
    "ph": " 2.92 ",
    "soils": ["Laurelwood Series "],
    "source_file": "AlloroRies17TechSheet.json",
    "ta": " 8.50 g/L ",
    "varietals": ["NULL"],
    "wine_name": ["Riesling"],
    "winery_id": "W-1",
    "winery_name": "Alloro",
    "year": "2017"
}, {
    "aging_process": "NULL",
    "bottle_id": 35,
    "cases_produced": 90,
    "clones": ["NULL"],
    "clusters": "NULL",
    "pct_alcohol": "12% ",
    "ph": "3.20 ",
    "soils": ["Sedimentary "],
    "source_file": "NV_dict_Blau_Pe\u0301tNat.json",
    "ta": "NULL",
    "varietals": ["100% Blaufr\u00e4nkisch "],
    "wine_name": ["NULL"],
    "winery_id": "W-6",
    "winery_name": "Minimus",
    "year": "2018"
}, {
    "aging_process": "15 months to 3 years in 2nd fill and neutral French oak barriques ",
    "bottle_id": 36,
    "cases_produced": 50,
    "clones": ["Old Wente", " Espiguette "],
    "clusters": "NULL",
    "pct_alcohol": "13.3% ",
    "ph": "3.42 ",
    "soils": ["NULL"],
    "source_file": "NV_Helix_Chardonnay.json",
    "ta": "NULL",
    "varietals": ["100% Chardonnay "],
    "wine_name": ["Chardonnay"],
    "winery_id": "W-6",
    "winery_name": "Minimus",
    "year": "2016"
}]

export default data;